media:
  input: public/assets/uploads
  output: /assets/uploads

content:
  # -------------------------
  # Posts (Markdown)
  # -------------------------
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [title, date, category, breaking, most_read]
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title (Arabic)
        type: string
        required: true

      - name: slug
        label: Slug (latin)
        type: string
        required: true
        description: "Used for the URL: /news/{slug}"
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lowercase latin letters, numbers, and dashes only. Replace spaces with -"

      - name: date
        label: Date & Time
        type: date
        required: true

      - name: description
        label: SEO Description
        type: text
        required: true

      - name: category_slug
        label: Category
        type: reference
        required: true
        options:
          collection: categories
          search: title
          value: "{slug}"
          label: "{title}"

      - name: author
        label: Author
        type: reference
        required: true
        options:
          collection: authors
          search: display_name
          value: "{slug}"
          label: "{display_name}"

      - name: featured_image
        label: Featured Image
        type: image
        required: true

      - name: type
        label: Post Type
        type: select
        required: false
        default: article
        options:
          values:
            - { value: article, label: "Article" }
            - { value: tv, label: "BeiruTalk TV" }

      - name: youtube
        label: YouTube URL (TV only)
        type: string
        required: false
        hint: "Paste a YouTube link (watch, youtu.be, shorts). Used only when Post Type = TV."

      - name: tags
        label: Tags
        type: reference
        required: false
        options:
          collection: tags
          multiple: true
          search: display_name
          value: "{slug}"
          label: "{display_name}"

      - name: hero
        label: Show in Hero
        type: boolean
        default: false

      - name: breaking
        label: Breaking News (Ticker)
        type: boolean
        default: false

      - name: breaking_text
        label: Breaking Ticker Text
        type: text
        required: false
        hint: "Optional short text for ticker. Falls back to title if empty."

      # ✅ Manual “Most Read”
      - name: most_read
        label: Most Read (الأكثر قراءة)
        type: boolean
        default: false

      - name: most_read_order
        label: Most Read Order
        type: number
        required: false
        hint: "Lower numbers appear first (1 = top)."

      - name: body
        label: Article Body
        type: rich-text
        required: true

  # -------------------------
  # Pins (Markdown)
  # -------------------------
  - name: pins
    label: دبوس
    type: collection
    path: content/pins
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [title, date]
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title (Arabic)
        type: string
        required: true

      - name: slug
        label: Slug (latin)
        type: string
        required: true
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lowercase latin letters, numbers, and dashes only. Replace spaces with -"

      - name: date
        label: Date & Time
        type: date
        required: true

      - name: featured_image
        label: Featured Image (optional)
        type: image
        required: false

      - name: body
        label: Content
        type: rich-text
        required: true

  # -------------------------
  # Backstage (Markdown)
  # -------------------------
  - name: backstage
    label: كواليس BeiruTalk
    type: collection
    path: content/backstage
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [title, date]
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title (Arabic)
        type: string
        required: true

      - name: slug
        label: Slug (latin)
        type: string
        required: true
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lowercase latin letters, numbers, and dashes only. Replace spaces with -"

      - name: date
        label: Date & Time
        type: date
        required: true

      - name: featured_image
        label: Featured Image (optional)
        type: image
        required: false

      - name: body
        label: Content
        type: rich-text
        required: true

  # -------------------------
  # Authors (JSON)
  # -------------------------
  - name: authors
    label: Authors
    type: collection
    path: content/data/authors
    format: json
    subfolders: false
    view:
      primary: slug
      fields: [slug, display_name]
      sort: [slug]
      default:
        sort: slug
        order: asc
    filename: "{primary}.json"
    fields:
      - name: slug
        label: ID (latin)
        type: string
        required: true
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lowercase latin letters, numbers, and dashes only. Replace spaces with -"

      - name: display_name
        label: Name (Arabic)
        type: string
        required: true

      - name: role
        label: Role
        type: string
        required: false

      - name: avatar
        label: Avatar
        type: image
        required: false

  # -------------------------
  # Tags (JSON)
  # -------------------------
  - name: tags
    label: Tags
    type: collection
    path: content/data/tags
    format: json
    subfolders: false
    view:
      primary: slug
      fields: [slug, display_name]
      sort: [slug]
      default:
        sort: slug
        order: asc
    filename: "{primary}.json"
    fields:
      - name: slug
        label: ID (latin)
        type: string
        required: true
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lowercase latin letters, numbers, and dashes only. Replace spaces with -"

      - name: display_name
        label: Name (Arabic)
        type: string
        required: true

  # -------------------------
  # Homepage blocks (JSON)
  # -------------------------
  - name: homepage
    label: Homepage Layout
    type: file
    path: content/data/homepage.json
    fields:
      - name: blocks
        label: Blocks
        type: object
        list: true
        fields:
          - name: type
            label: Block Type
            type: select
            required: true
            options:
              values:
                - { value: categorySpotlight, label: categorySpotlight }
                - { value: threeCards, label: threeCards }
                - { value: horizontal, label: horizontal }
                - { value: textList, label: textList }
                - { value: videoStrip, label: videoStrip }

          - name: title
            label: Title (Arabic)
            type: string
            required: true

          - name: slug
            label: Category Slug (optional for videoStrip)
            type: reference
            required: false
            hint: "Leave empty for videoStrip."
            options:
              collection: categories
              search: title
              value: "{slug}"
              label: "{title}"

          - name: href
            label: Custom Href (optional)
            type: string
            required: false
            hint: "Optional override link. Example: /videos"

          - name: limit
            label: Limit
            type: number
            required: false

  # -------------------------
  # Menus (JSON)
  # -------------------------
  - name: menus
    label: Menus
    type: file
    path: content/data/menus.json
    fields:
      - name: header
        label: Header Menu
        type: object
        list: true
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: true

          - name: type
            label: Type
            type: select
            required: true
            options:
              values:
                - { value: home, label: home }
                - { value: category, label: category }
                - { value: custom, label: custom }

          - name: label
            label: Label (Arabic)
            type: string
            required: true

          - name: slug
            label: Category Slug
            type: string
            required: false
            hint: "Used when type=category. Example: lebanon"

          - name: href
            label: Custom Href
            type: string
            required: false
            hint: "Used when type=custom or to override. Example: /about"

      - name: footerSections
        label: Footer Categories Menu
        type: object
        list: true
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: true

          - name: type
            label: Type
            type: select
            required: true
            options:
              values:
                - { value: home, label: home }
                - { value: category, label: category }
                - { value: custom, label: custom }

          - name: label
            label: Label (Arabic)
            type: string
            required: true

          - name: slug
            label: Category Slug
            type: string
            required: false

          - name: href
            label: Custom Href
            type: string
            required: false

  # -------------------------
  # Categories (JSON)
  # -------------------------
  - name: categories
    label: Categories
    type: collection
    path: content/data/categories
    format: json
    subfolders: false
    view:
      primary: slug
      fields: [slug, title]
      sort: [slug]
      default:
        sort: slug
        order: asc
    filename: "{primary}.json"
    fields:
      - name: slug
        label: Slug
        type: string
        required: true
      - name: title
        label: Title (Arabic)
        type: string
        required: true

  # -------------------------
  # Site Contact (JSON)
  # -------------------------
  - name: site_contact
    label: Site Contact
    type: file
    path: content/data/siteContact.json
    fields:
      - name: email
        label: Email
        type: string
      - name: whatsapp
        label: WhatsApp
        type: string
      - name: socials
        label: Socials
        type: object
        fields:
          - { name: facebook, type: string }
          - { name: instagram, type: string }
          - { name: x, type: string }
          - { name: youtube, type: string }
          - { name: tiktok, type: string }
          - { name: linkedin, type: string }

  # -------------------------
  # Ads (JSON)
  # -------------------------
  - name: ads
    label: Ads
    type: file
    path: content/data/ads.json
    fields:
      - name: adsense
        label: AdSense
        type: object
        fields:
          - { name: enabled, type: boolean, default: false }
          - { name: client, type: string }

      - name: slots
        label: Slots
        type: object
        list: true
        fields:
          - { name: id, type: string, required: true }
          - { name: enabled, type: boolean, default: true }
          - { name: label, type: string }

          - name: type
            label: Type
            type: select
            required: true
            options:
              values:
                - { value: custom, label: custom }
                - { value: adsense, label: adsense }

          - name: custom
            label: Custom
            type: object
            fields:
              - { name: image, type: image }
              - { name: href, type: string }
              - { name: alt, type: string }
              - { name: openInNewTab, type: boolean, default: true }

          - name: adsense
            label: AdSense
            type: object
            fields:
              - { name: slot, type: string }
              - { name: format, type: string }
              - { name: responsive, type: boolean, default: true }

  # -------------------------
  # Head Inject (JSON)
  # -------------------------
  - name: head
    label: Head Injects
    type: file
    path: content/data/head.json
    fields:
      - name: enabled
        label: Enabled
        type: boolean
        default: true

      - name: meta
        label: Meta tags
        type: object
        list: true
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: true
          - name: name
            label: Name
            type: string
            required: true
          - name: content
            label: Content
            type: string

      - name: scripts
        label: External scripts
        type: object
        list: true
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: false
          - name: id
            label: ID
            type: string
            required: true
          - name: strategy
            label: Strategy
            type: select
            required: false
            options:
              values:
                - { value: beforeInteractive, label: beforeInteractive }
                - { value: afterInteractive, label: afterInteractive }
                - { value: lazyOnload, label: lazyOnload }
            default: afterInteractive
          - name: src
            label: Script src
            type: string
            required: true
          - name: crossOrigin
            label: crossOrigin
            type: select
            required: false
            options:
              values:
                - { value: anonymous, label: anonymous }
                - { value: use-credentials, label: use-credentials }

      - name: inlineScripts
        label: Inline scripts
        type: object
        list: true
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: false
          - name: id
            label: ID
            type: string
            required: true
          - name: strategy
            label: Strategy
            type: select
            required: false
            options:
              values:
                - { value: beforeInteractive, label: beforeInteractive }
                - { value: afterInteractive, label: afterInteractive }
                - { value: lazyOnload, label: lazyOnload }
            default: afterInteractive
          - name: code
            label: Code
            type: text

settings:
  hide: true
  content:
    merge: true
